Handbook:
  - Development:
    - Development Environment and Tools:
      - Environment Setup:
        - Vagrant and VirtualBox
      - Automation Scripts
      - Common File Formats:
        - YAML
        - JSON
        - Markdown
        - XML
    - Code Development Lifecycle
    - Software Development Processes
  - Production:
    - Deployment Management
    - DevOps
  - Coding:
    - Code Quality
    - Development Models
    - Design patterns
  - Soft Skills (The Human Factor):
    - How to effectively interact with other people
