# Git

Git is an open source distributed version control system originally developed by Linus Torvalds to 
support the development of the linux kernel.


## Table of Contents

- [Git Overview][1]
- [Git Installation][2]
- [Getting Started with Git][3]

---

[1]: /Guides/Git/Git%20Overview
[2]: /Guides/Git/Git%20Installation
[3]: /Guides/Git/Getting%20Started%20with%20Git
