intro: |
  Git is an open source distributed version control system originally developed by Linus Torvalds to 
  support the development of the linux kernel.

guides:
  - "[Git Overview](/Guides/Git/Git%20Overview)"
  - "[Git Installation](/Guides/Git/Git%20Installation)"
  - "[Getting Started with Git](/Guides/Git/Getting%20Started%20with%20Git)"
